python_modules:
  - name: ara
    state: present
  - name: autopep8
    state: present
  - name: beautysh
    state: present
  - name: django
    state: present
  - name: flask
    state: present
  - name: GitPython
    state: present
  - name: ipaddr
    state: present
  - name: jmespath
    state: present
  - name: keyring
    state: present
  - name: molecule
    state: absent
  - name: netaddr
    state: present
  - name: nmap
    state: present
  - name: passlib
    state: present
  - name: pygithub3
    state: present
  - name: pylama
    state: present
  - name: pylint
    state: present
  - name: pyOpenSSL
    state: present
  - name: python-consul
    state: present
  - name: python-language-server[all]
    state: present
  - name: pyvmomi
    state: present
  - name: pywinrm
    state: present
  - name: requests
    state: present
  - name: TerraformToAnsibleInventory
    state: present
  - name: testinfra
    state: present
  - name: tox
    state: present
